### PR TITLE
fix error

### PR DESCRIPTION
**Pull request by Red171js**
hello i got this error:  
```js

/home/container/node_modules/slashcord/src/index.ts:1
import { Client, Collection } from "discord.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/container/index.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
```

### CODE REVIEW

**Comment by MysticIsSus** [comment]
what are you trying to do that caused this error

**Comment by Red171js** [comment]
> what are you trying to do that caused this error

I just installed slashcord and put this: `client.on("ready", () => {

   // Initialize Slashcord and it's arguments.

   new Slashcord(client, "commands")

   .setTestServers(["830481105261821952"])

   .setBotOwners(["605162125027049472"])
   
})`

**Comment by Red171js** [comment]
ps: I shouldn't have corrected that file, oops sorry

**Comment by MysticIsSus** [comment]
I have fixed it, apparently one of our devs put the wrong main file, do `npm i slashcord@latest`

**Comment by Red171js** [comment]
new error: ```
(node:36) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).setTestServers is not a function
    at Client.<anonymous> (/home/container/index.js:87:5)
    at Client.emit (events.js:388:22)
    at WebSocketManager.triggerClientReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:376:20)
    at WebSocketShard.checkReady (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/discord.js/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:376:20)
    at Receiver.receiverOnMessage (/home/container/node_modules/discord.js/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:376:20)
    at Receiver.dataMessage (/home/container/node_modules/discord.js/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/home/container/node_modules/discord.js/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/home/container/node_modules/discord.js/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/home/container/node_modules/discord.js/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.socketOnData (/home/container/node_modules/discord.js/node_modules/ws/lib/websocket.js:910:35)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
```

**Comment by MysticIsSus** [comment]
come to the support server > https://discord.gg/2zAGKE3t

**Pull request closed without merging**
